"use client";
import React, { useState, useEffect } from 'react';

export default function Dashboard() {
  const [vaultState, setVaultState] = useState({
    tvl: "0.00",
    apy: "--%",
    cumulative_yield: "0.0000",
    recent_events: ["[System] Initializing daemon link..."]
  });

  useEffect(() => {
    const fetchState = async () => {
      try {
        // Fetch the JSON file generated by the Python daemon with a cache-buster
        const response = await fetch(`/vault_state.json?t=${new Date().getTime()}`, { 
          cache: 'no-store' 
        });
        
        if (response.ok) {
          const data = await response.json();
          setVaultState(data);
        }
      } catch (error) {
        console.error("Error fetching vault state:", error);
      }
    };

    // Fetch immediately, then check every 5 seconds for updates
    fetchState();
    const interval = setInterval(fetchState, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 p-6 md:p-12 font-sans selection:bg-zinc-800">
      <main className="max-w-6xl mx-auto space-y-8">
        
        {/* Header Block */}
        <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-zinc-800">
          <div>
            <h1 className="text-xl font-medium tracking-tight text-zinc-200">HYPE Vault Engine</h1>
            <p className="text-xs text-zinc-500 font-mono mt-0.5">Status: Operational // Node v1.0.0</p>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-zinc-900 border border-zinc-800 rounded-lg text-xs font-mono text-emerald-400">
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Daemon Connected
          </div>
        </header>

        {/* Metrics Grid */}
        <section className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-5 bg-[#121214] border border-zinc-800 rounded-xl space-y-2">
            <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Total Value Locked</p>
            <p className="text-3xl font-light tracking-tight text-zinc-100">{vaultState.tvl} <span className="text-sm font-normal text-zinc-500 font-mono">HYPE</span></p>
          </div>
          
          <div className="p-5 bg-[#121214] border border-zinc-800 rounded-xl space-y-2">
            <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Staking Rewards (APY)</p>
            <p className="text-3xl font-light tracking-tight text-emerald-400">{vaultState.apy}</p>
          </div>

          <div className="p-5 bg-[#121214] border border-zinc-800 rounded-xl space-y-2">
            <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Cumulative Yield</p>
            <p className="text-3xl font-light tracking-tight text-zinc-100">{vaultState.cumulative_yield} <span className="text-sm font-normal text-zinc-500 font-mono">HYPE</span></p>
          </div>
        </section>

        {/* Activity & Chart Section */}
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 p-6 bg-[#121214] border border-zinc-800 rounded-xl h-64 flex flex-col justify-between">
            <h2 className="text-sm font-medium tracking-tight text-zinc-400">Performance History</h2>
            <div className="flex-1 flex items-center justify-center text-xs text-zinc-600 font-mono">
              [ Yield Curve Visualization Coming Soon ]
            </div>
          </div>

          {/* Terminal Daemon Logs Output */}
          <div className="p-6 bg-[#121214] border border-zinc-800 rounded-xl flex flex-col h-64">
            <h2 className="text-sm font-medium tracking-tight text-zinc-400 mb-4">Automation Events</h2>
            <div className="flex-1 bg-black/40 border border-zinc-900 rounded-lg p-3 font-mono text-[11px] text-zinc-400 overflow-y-auto space-y-2">
              {vaultState.recent_events.map((event, index) => (
                <p key={index} className={event.includes("Sweep") ? "text-emerald-500/80" : "text-zinc-500"}>
                  {event}
                </p>
              ))}
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
